import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/navbar";
import Script from "next/script";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Doward Caparas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-[1440px] mx-auto">
      <body className={`${montserrat.className} antialiased dark:bg-[#171717] bg-gray-50 dark:text-white
      `}>
        <NavBar />
        {children}
        {/* Embedded Chatbot Script */}
        <Script
          id="chatbot-config"
          dangerouslySetInnerHTML={{
            __html: `
      window.embeddedChatbotConfig = {
        chatbotId: "${process.env.NEXT_PUBLIC_CHATBOT_ID}",
        domain: "${process.env.NEXT_PUBLIC_CHATBOT_DOMAIN}"
      };
    `,
          }}
        />
        <Script
          src="https://www.chatbase.co/embed.min.js"
          strategy="lazyOnload" // Ensures it loads after the page
        />
         <footer className="py-9 mx-0 bottom-0 z-30 right-0 left-0">
        <p className="text-center text-sm">&copy; 2025 Dounhuward B. Caparas All rights reserved.</p>
      </footer>
      </body>
    </html>
  );
}
