import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/navbar";
import Script from "next/script";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Doward Caparas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-[1440px] mx-auto">
      <body className={`${montserrat.className} antialiased dark:bg-[#0a0a0a] dark:text-white`}>
        <NavBar />
        <div className="fixed inset-0 -z-10 flex items-center justify-center">
          <div className="h-[600px] w-[600px] rounded-full bg-gray-500 dark:bg-green-200 opacity-10 blur-[150px]" />
        </div>

        {children}
        {/* Embedded Chatbot Script */}
        <Script
          id="chatbot-config"
          dangerouslySetInnerHTML={{
            __html: `
      window.embeddedChatbotConfig = {
        chatbotId: "${process.env.NEXT_PUBLIC_CHATBOT_ID}",
        domain: "${process.env.NEXT_PUBLIC_CHATBOT_DOMAIN}"
      };
    `,
          }}
        />
        <Script
          src="https://www.chatbase.co/embed.min.js"
          strategy="lazyOnload" // Ensures it loads after the page
        />
      </body>
    </html>
  );
}
