import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/navbar";

const montserrat = Montserrat({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Doward Caparas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-[1440px] mx-auto">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
